version: '3.1'

services:

  database:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=VpGdxrtBbzs0Zgxn5o
      - POSTGRES_DB=fifa
