import { Route } from "@/lib/route";
import { Container } from "@nextui-org/react";
import Head from "next/head";
import Footer from "./footer";
import Navbar from "./navbar";

interface Props {
  title: string;
  children?: React.ReactNode;
}

const DefaultLayout = ({ title, children }: Props) => {
  const routes = [
    {
      title: "Tweets",
      href: "/tweets",
    },
    {
      title: "World Cup 2022",
      href: "/world-cup-2022",
    },
    {
      title: "Leaderboard",
      href: "/leaderboard",
    },
    {
      title: "About",
      href: "/about",
    },
  ] as Route[];

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar routes={routes} />
        {children}
        <Footer />
      </main>
    </>
  );
};

export default DefaultLayout;
