server:
  port: 8080
spring:
  application:
    name: fifa-api
  datasource:
    url: jdbc:postgresql://localhost:5432/fifa
    username: backend
    password: VpGdxrtBbzs0Zgxn5o
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false